title: GovEx Labs
url: http://labs.centerforgov.org
description: Our playground for experimentation and fluid content.
logo: /images/govex-labs-purple.svg
repository: govex/govex.github.io

# never include the trailing slash in baseurl (ex: "site/")
baseurl: 

# navigation configuration
navigation:
  - title: <span class="glyphicon glyphicon-book"></span> Guides
    url: guides/
  - title: <span class="glyphicon glyphicon-user"></span> City Trainings
    url: city-trainings/
  - title: <span class="glyphicon glyphicon-cog"></span> Civic Data Standards
    url: open-data/civic-data-standards/
    
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
    scope:
      path: "open-data-portal-requirements"
    values:
      layout: collaboration
      
# Make redcarpet behave like GitHub Flavored Markdown 
redcarpet: 
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

gems:
  - jekyll-redirect-from
